create table if not exists public.app_config (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  ios_latest_version text,
  ios_minimum_version text,
  ios_store_url text,
  android_latest_version text,
  android_minimum_version text,
  android_store_url text
);

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'set_app_config_updated_at'
  ) then
    create trigger set_app_config_updated_at
    before update on public.app_config
    for each row
    execute procedure public.set_updated_at();
  end if;
end;
$$;

alter table public.app_config enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'app_config'
      and policyname = 'App config is publicly readable'
  ) then
    create policy "App config is publicly readable"
      on public.app_config
      for select
      using (true);
  end if;
end;
$$;
