// @ts-check
import { defineConfig } from 'astro/config';

import astroLlmsTxt from '@4hse/astro-llms-txt';
import react from '@astrojs/react';
import tailwindcss from '@tailwindcss/vite';

const llmsPublicPages = [
  '/',
  'about/',
  'delete-account/',
  'glp-1-injection-tracker/',
  'guides/**',
  'glossary/**',
  'printable-glp-1-tracker/',
  'privacy/',
  'support/',
  'terms/',
];

const llmsPriorityPages = ['/', 'glp-1-injection-tracker/', 'about/'];

const llmsIgnoreSelectors = ['nav', 'script', 'style', '[data-llms-ignore]'];

const llmsDetails = [
  'Use these pages for product overview, support, privacy, terms, account deletion, GLP-1 treatment guides, glossary definitions, and company information.',
  '',
  '## 1) Product Snapshot',
  'Glu is a GLP-1 tracking app for people before, during, and after treatment. It keeps shot reminders, dose history, injection sites, hydration, cravings, symptoms, mood, exercise, meals, side effects, and weight progress in one calm place.',
  '',
  '### What Glu is',
  'Glu turns a complicated treatment routine into a clear daily record. It helps users stay consistent, spot patterns, and walk into appointments with something better than memory.',
  '',
  '### Who it is for',
  '- People starting GLP-1 treatment and trying to build a routine from day one.',
  '- People adjusting doses, side effects, or appetite changes during treatment.',
  '- People maintaining progress or tapering into life after treatment.',
  '- People after treatment who want to keep the habit going and visualize what changed.',
  '- People who struggle with routine and want Glu to remind them to stay on track while making the pattern visible.',
  '- People who want a paper-first option before moving to the app.',
  '',
  '### Positioning',
  'Glu is the all-in-one GLP-1 tracker built for the medication journey. It is dead simple to use, focused on useful patterns, and designed to make progress something you can see and share.',
  '',
  '## 2) The Problem',
  'GLP-1 treatment is not just a medication. It creates a weekly workflow: shot day, rotation, symptoms, appetite changes, meal decisions, water intake, exercise, and the question of whether the trend is actually moving. Generic health apps do not organize that context well.',
  '',
  '### Painful problems Glu solves',
  '- Overwhelm from tracking dose, site, symptoms, meals, water, movement, and weight in separate places.',
  '- Side effect uncertainty because nausea, fatigue, cravings, and mood changes are hard to remember accurately.',
  '- Plateau anxiety when daily weigh-ins hide the real trend.',
  '- Appointment friction because users arrive without a clear history.',
  '- Maintenance and after-treatment drift when progress stops feeling visible.',
  '',
  '## 3) Personas',
  '### Primary persona cluster',
  '- New starters who want structure from the first dose.',
  '- Adjusters who need to understand what changed after a dose step.',
  '- Maintainers who want to protect results.',
  '- Weaners or after-treatment users who want to preserve habits and catch rebound early.',
  '- Paper-first users who want a printable tracker before committing to the app.',
  '',
  '### Emotional transformation',
  'From overwhelmed and guessing to clear, consistent, and able to explain what is happening.',
  '',
  '## 4) Value Proposition & Differentiation',
  '### Core promise',
  'Dump the details of treatment into one place. Glu organizes the routine so the user can act on it.',
  '',
  '### Core surfaces',
  '- Home overview for the whole day and week.',
  '- GLP-1 injection tracker for dose, site, weight, symptoms, and habit logging.',
  '- Glow Up for side-by-side progress visuals that make change easy to see.',
  '- Portion Check for deciding how much of a meal fits the day, especially useful after treatment when habits are still being rebuilt.',
  '- Snap Macros for tracking macros and building better habits.',
  '- Printable GLP-1 tracker for paper-first users.',
  '- Guides and glossary pages for treatment education.',
  '',
  '### Differentiators',
  '- Built specifically for GLP-1 routines rather than generic wellness logging.',
  '- Includes the details that actually matter: hydration, cravings, symptoms, mood, exercise, meals, and weight progress.',
  '- Supports before, during, and after treatment use cases, including visual progress and meal portioning after treatment.',
  '- Connects the routine to useful context instead of asking users to build the system themselves.',
  '',
  '## 5) Solution',
  '### Core loop',
  '1. Track a shot and its dose.',
  '2. Log the week as it happens: water, cravings, symptoms, mood, exercise, meals, and weight.',
  '3. Use trend views and guides to interpret what happened.',
  '4. Bring the record to an appointment or use it to adjust the next week.',
  '',
  '### Current Core Features',
  '- Shot reminders and dose history.',
  '- Injection site rotation tracking.',
  '- Weight tracking with progress visibility.',
  '- Hydration tracking.',
  '- Cravings tracking.',
  '- Symptom logging with timing context.',
  '- Mood tracking.',
  '- Exercise tracking.',
  '- Meal and nutrition logging.',
  '- Portion Check for quick meal-portion guidance.',
  '- Glow Up for before/after progress visuals.',
  '- Snap Macros for fast macro tracking and habit building.',
  '- Doctor report export for sharing the last 90 days of medication and symptom history.',
  '- Progress and habits logging.',
  '- Printable shot tracker.',
  '- GLP-1 guides and glossary content.',
  '',
  '## 6) Benefits',
  '### Functional benefits',
  '- One place for the full treatment routine.',
  '- Better understanding of side effects and appetite changes.',
  '- Clearer weight progress instead of daily noise.',
  '- Better visual proof of change with Glow Up.',
  '- Faster portion decisions with Portion Check.',
  '- Easier appointment prep.',
  '',
  '### Emotional benefits',
  '- Less guessing.',
  '- Less shame and fewer “did I miss something?” moments.',
  '- More confidence that the user is seeing the real pattern.',
  '',
  '## 7) Key Use Cases',
  '1. Starting treatment and building a routine.',
  '2. Logging shot day and keeping track of rotation.',
  '3. Understanding nausea, cravings, mood, hydration, or exercise changes across a dose week.',
  '4. Watching weight progress during a plateau.',
  '5. Using Glow Up to visualize change after treatment or at maintenance.',
  '6. Using Portion Check to decide how much of a meal fits the day, especially after treatment.',
  '7. Preparing for a doctor visit with a clearer record.',
  '8. Using the printable tracker before the app becomes a habit.',
  '9. Staying organized before, during, and after treatment.',
  '',
  '## 8) Trust and Privacy',
  '- AI features are optional and opt-in.',
  '- Glu does not sell personal data.',
  '- Users can review the privacy policy and terms for storage, subscriptions, and account deletion details.',
].join('\n');

// https://astro.build/config
export default defineConfig({
  site: 'https://myglu.health',
  integrations: [
    react(),
    astroLlmsTxt({
      title: 'Glu',
      description:
        'Glu is a GLP-1 tracking app for reminders, dose history, meals, weight progress, hydration, cravings, symptoms, mood, exercise, and daily habits.',
      details: llmsDetails,
      optionalLinks: [
        {
          label: 'Home',
          url: 'https://myglu.health/',
          description: 'Main landing page for the app',
        },
        {
          label: 'About',
          url: 'https://myglu.health/about',
          description: 'Company and product overview',
        },
        {
          label: 'App Store',
          url: 'https://apps.apple.com/us/app/glu-glp-1-weight-loss-tracker/id6761419458',
          description: 'Install Glu for iPhone',
        },
        {
          label: 'Google Play',
          url: 'https://play.google.com/store/apps/details?id=ventures.layline.glu',
          description: 'Install Glu for Android',
        },
        {
          label: 'Support',
          url: 'https://myglu.health/support',
          description: 'Support and contact page',
        },
        {
          label: 'Privacy Policy',
          url: 'https://myglu.health/privacy',
          description: 'Privacy and data handling policy',
        },
        {
          label: 'Terms of Service',
          url: 'https://myglu.health/terms',
          description: 'Terms, subscriptions, and legal terms',
        },
        {
          label: 'Delete Account',
          url: 'https://myglu.health/delete-account',
          description: 'Account deletion instructions',
        },
        {
          label: 'GLP-1 Guides',
          url: 'https://myglu.health/guides',
          description: 'Practical, evidence-based guides for life on GLP-1 medications',
        },
        {
          label: 'GLP-1 Glossary',
          url: 'https://myglu.health/glossary',
          description: 'Plain-language definitions of GLP-1 treatment terms',
        },
        {
          label: 'GLP-1 Injection Tracker',
          url: 'https://myglu.health/glp-1-injection-tracker',
          description: 'How Glu tracks doses, injection sites, weight, and side effects',
        },
      ],
      docSet: [
        {
          title: 'Glu site index',
          description: 'Compact index of the key public pages on myglu.health.',
          url: '/llms-small.txt',
          include: llmsPublicPages,
          onlyStructure: true,
          promote: llmsPriorityPages,
          ignoreSelectors: llmsIgnoreSelectors,
        },
        {
          title: 'Glu full site content',
          description: 'Full content for the key public pages on myglu.health.',
          url: '/llms-full.txt',
          include: llmsPublicPages,
          promote: llmsPriorityPages,
          ignoreSelectors: llmsIgnoreSelectors,
        },
      ],
    }),
  ],

  vite: {
    plugins: [tailwindcss()],
  }
});
